services:
  scheddy:
    image: celeo/scheddy:latest
    ports:
      - 3000:3000
  db:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: c4c76a7deb9b709219f
      MYSQL_DATABASE: scheddy
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db_data:
